-- Generated by hyprconf2lua v1.4.0 (Corrigido)
-- @module 'hl'

-- Rules de Layer
hl.layer_rule({ "monitor HDMI-A-1", "virtual-keyboard" })
hl.layer_rule({ "noanim", "virtual-keyboard" })

-- Monitores
hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@60",
    position = "1920x0",
    scale    = 1,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@60",
    position = "0x0",
    scale    = 1,
})

-- Workspaces orientation
hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "2", monitor = "eDP-1" })

-- Configurações Gerais
hl.config({
    input = {
        kb_layout = "br",
        numlock_by_default = true,
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
            disable_while_typing = true,
        },
        sensitivity = 0,
    },
})

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 2,
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(8f00ffee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 10,
        blur = {
            enabled = true,
            size = 5,
            passes = 1,
        },
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
    },
})

hl.config({
    animations = { enabled = true },
})

hl.config({
    dwindle = { preserve_split = true },
})

hl.config({
    master = { new_status = "master" },
})

hl.config({
    misc = { disable_hyprland_logo = true },
})

-- Env vars
hl.env("SSH_ASKPASS", "/usr/bin/ksshaskpass")
hl.env("SSH_ASKPASS_REQUIRE", "prefer")

-- Modificador Principal
local mainMod = "SUPER"

-- Keybindings
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("footclient")) -- 36 = Return
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("footclient"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("nwgbar"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("thunar"))
hl.bind(mainMod .. " + SHIFT + space", hl.dsp.window.float())
hl.bind("SUPER + D", hl.dsp.exec_cmd("pkill wofi || wofi --normal-window --show drun --allow-images"),
    { repeating = true })
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("emote"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("nwg-drawer -mb 10 -mr 10 -ml 10 -mt 10"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + P", hl.dsp.layout("togglesplit"))

-- Teclas de Função (F1 - F12)
hl.bind(mainMod .. " + F1", hl.dsp.exec_cmd("brave"))
hl.bind(mainMod .. " + F2", hl.dsp.exec_cmd("thunderbird"))
hl.bind(mainMod .. " + F3", hl.dsp.exec_cmd("thunar"))
hl.bind(mainMod .. " + F4", hl.dsp.exec_cmd("geany"))
hl.bind(mainMod .. " + F5", hl.dsp.exec_cmd("github-desktop"))
hl.bind(mainMod .. " + F6", hl.dsp.exec_cmd("gparted"))
hl.bind(mainMod .. " + F7", hl.dsp.exec_cmd("inkscape"))
hl.bind(mainMod .. " + F8", hl.dsp.exec_cmd("blender"))
hl.bind(mainMod .. " + F9", hl.dsp.exec_cmd("meld"))
hl.bind(mainMod .. " + F10", hl.dsp.exec_cmd("joplin-desktop"))
hl.bind(mainMod .. " + F11", hl.dsp.exec_cmd("snapper-tools"))
hl.bind(mainMod .. " + F12", hl.dsp.exec_cmd("galculator"))

-- Foco de janelas
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

-- Workspaces (1 - 10)
for i = 1, 9 do
    hl.bind(mainMod .. " + " .. i, hl.dsp.focus({ workspace = i }))
    hl.bind("ALT + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }, { follow = false }))
end
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind("ALT + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }, { follow = false }))

-- Scroll do mouse para workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Mover/Redimensionar com mouse
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Layer rules
hl.layer_rule({
    match = { namespace = "waybar" },
    ignore_alpha = 0.5,
    blur = true
})

hl.layer_rule({
    match = { class = "~nwgbar" },
    blur = true,
    dim_around = false,
})

hl.layer_rule({
    match = { namespace = "swaync-control-center" },
    blur = false
})

hl.layer_rule({
    match = { namespace = "swaync-notification-window" },
    blur = false
})

-- Window rules
hl.window_rule({
    match = { class = "^(thunar)$" },
    opacity = "0.85 override 0.85 override"
})

hl.window_rule({
    match = { class = "^(dev.zed.Zed)$" },
    workspace = "3",
    monitor = "HDMI-A-1"
})

hl.window_rule({
    match = { class = "^(ksshaskpass)$" },
    float = true,
    center = true,
    size = { 450, 200 },
    opacity = "0.85 override 0.85 override",
    dim_around = true,
    -- bordercolor = rgb(#ff79c6)
})

hl.window_rule({
    match = { title = "^(Picture in picture)$" },
    float = true,
    size = { 911, 517 }
})

hl.window_rule({
    match = { class = "^(vlc)$" },
    float = true,
    -- fullscreen_state = 0,
    -- fullscreen = false,
    size = { 911, 517 },
    -- center = true
})

-- Controle de Mídia e Brilho
hl.bind("XF86AudioLowerVolume",
    hl.dsp.exec_cmd("pamixer --decrease 5; notify-send Volume: $(pamixer --get-volume) -t 500"))
hl.bind("XF86AudioRaiseVolume",
    hl.dsp.exec_cmd("pamixer --increase 5; notify-send Volume: $(pamixer --get-volume) -t 500"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer --toggle-mute; notify-send Volume: Toggle-mute -t 500"))
hl.bind("XF86AudioMicMute",
    hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle; notify-send System Mic: Toggle-mute -t 500"))

hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("brave"))
hl.bind(mainMod .. " + M", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen_state({ internal = 0, client = 2 }))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -c backlight set 5%-"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -c backlight set +5%"))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("killall -9 wpaperd && wpaperd"))

-- Captura de tela
hl.bind("Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | swappy -f -"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd(". config/hypr/scripts/screenshot_window.sh"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(". config/hypr/scripts/screenshot_display.sh"))

-- Submap: Resize
hl.bind(mainMod .. " + R", hl.dsp.submap("resize"))
hl.define_submap("resize", function()
    hl.bind("escape", hl.dsp.submap("reset"))
end)

-- Mover Janelas (Corrigido com dispatcher)
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))

-- Workspace Especial
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.workspace.toggle_special("magic"))

-- Clipboard & Mídia
hl.bind("SUPER + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("footclient -e ~/.local/bin/bear/implement_gum.sh enable"))
hl.bind(mainMod .. " + I", hl.dsp.exec_cmd(". local/bin/calamares.sh"))

-- Variáveis de Ambiente
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

-- Dispositivos
hl.device({
    name = "jp-usb-keyboard",
    kb_layout = "br",
    kb_variant = "abnt2",
})

hl.bind(mainMod .. " + z", hl.dsp.exec_cmd("wtype ''"))

-- Inicialização
hl.on("hyprland.start", function()
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("~/.local/bin/mpris-notifier.sh")
    hl.exec_cmd("wpaperd")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("foot --server")
    hl.exec_cmd("xrdb -load ~/.Xresources")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("apply-gsettings")
    hl.exec_cmd(". local/bin/battery_warn.sh")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("ssh-add </dev/null")
end)
